@localhost = http://localhost:3000

#### GET recuperar um conector específico
GET {{localhost}}/connectors/pepino/configs
Content-Type: application/json

#### GET recuperar nome dos conectores disponíveis
GET {{localhost}}/connectors
Content-Type: application/json

#### POST remover um conector específico
POST {{localhost}}/connectors
Content-Type: application/json

{
    "name": "abobora",
    "delimiter": ";",
    "topic": "this.is-my.topic.name",
    "fieldNames": "fruta1;fruta2;fruta3;fruta4;fruta5;fruta6;fruta7",
    "filters" : {
        "sequence" : "renameFruta1;removeFruta2;appendFruta3e4;renameFruta5;removeFruta6", 
        "jobs": [
            {
                "name" : "renameFruta1", 
                "type" : "rename", 
                "field" : "fruta1", 
                "target" : "frutaUm"
            }, 
            {
                "name" : "removeFruta2", 
                "type" : "remove", 
                "field" : "fruta2"
            }, 
            {
                "name" : "appendFruta3e4", 
                "type" : "append", 
                "firstField" : "fruta3", 
                "secondField" : "fruta4", 
                "newFieldName" : "fruta3e4"
            }, 
            {
                "name" : "renameFruta5", 
                "type" : "rename", 
                "field" : "fruta5", 
                "target" : "frutaCinco"
            }, 
            {
                "name" : "removeFruta6", 
                "type" : "remove", 
                "field" : "fruta6"
            }
        ]
    },
    "retry" : false
}

#### DELETE remover um conector específico
DELETE {{localhost}}/connectors/teste
Content-Type: application/json
