@localhost = http://localhost:3000

#### GET recuperar um conector específico
GET {{localhost}}/connectors/fruits
Content-Type: application/json

#### GET recuperar nome dos conectores disponíveis
GET {{localhost}}/connectors
Content-Type: application/json

#### POST remover um conector específico
POST {{localhost}}/connectors
Content-Type: application/json

{
    "name": "test",
    "delimiter": ";",
    "topic": "event-streaming.connector.teste",
    "schema": 100100,
    "fieldNames": "c1;c2;c3;c4;c5;c6;c7;c8;c9;c10;c11;c12",
    "propertiesPosition": [0,1,2,3,4,5,6,7,8,9,10,11,12],
    "filters" : {
        "sequence" : "rename;remove;removeArray;append;appendWithValueStart;appendWithValueEnd;drop;positionedDrop;parseInt;parseString", 
        "jobs": [
            {
                "name" : "rename", 
                "type" : "rename", 
                "fieldTarget" : "c1", 
                "newFieldName" : "campo1"
            }, 
            {
                "name" : "remove", 
                "type" : "remove", 
                "field" : "c2"
            }, 
            {
                "name" : "removeArray", 
                "type" : "remove", 
                "field" : ["c3","c4"]
            }, 
            {
                "name" : "append", 
                "type" : "append", 
                "firstField" : "c5", 
                "secondField" : "c6", 
                "newFieldName" : "c56"
            }, 
            {
                "name" : "appendWithValueStart", 
                "type" : "appendWithValue", 
                "firstField" : "c7", 
                "stringToAppend": "test",
                "newFieldName" : "frutaCinco",
                "position": "start"
            }, 
            {
                "name" : "appendWithValueEnd", 
                "type" : "appendWithValue", 
                "firstField" : "c8", 
                "stringToAppend": "test",
                "newFieldName" : "frutaCinco",
                "position": "end"
            }, 
            {
                "name" : "drop", 
                "type" : "drop", 
                "fieldTarget": "c9",
                "comparison": {
                    "operator": "===",
                    "value": "0"
                }
            }, 
            {
                "name" : "positionedDrop", 
                "type" : "positionedDrop", 
                "fieldTarget": "c10",
                "comparison": {
                    "operator": "===",
                    "value": "0",
                    "digit": 0
                }
            }, 
            {
                "name" : "parseInt", 
                "type" : "parse", 
                "fieldTarget": "c11",
                "parseType": "int"
            }, 
            {
                "name" : "parseString", 
                "type" : "parse", 
                "fieldTarget": "c12",
                "parseType": "string"
            }
        ]
    },
    "retry" : false
}

#### DELETE remover um conector específico
DELETE {{localhost}}/connectors/fruits
Content-Type: application/json
